config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :school, only: [:new, :create, :update], path_names: {new: ''}
  root to: 'home#index'

  resources :units, except: [:show] do
    resources :teachers
    resources :students
    resources :courses
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :unit, counter_cache: true
  has_many :legal_guardians, inverse_of: :student, dependent: :destroy
  has_and_belongs_to_many :courses

  accepts_nested_attributes_for :legal_guardians, allow_destroy: true
  
  validates :unit, presence: true
  validates :name, presence: true
  validates :registration, presence: true, uniqueness: true
  validates :birthday, presence: true
  validates :legal_guardians , length: { minimum: 1 }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include SetSchool
  before_action :set_unit
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = @unit.students.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @student = @unit.students.build
  end

  def edit
  end

  def create
    @student = @unit.students.build(student_params)
    if @student.save
      redirect_to unit_students_path(@unit), notice: 'Estudante foi criado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @student.update(student_params)
      redirect_to unit_students_path(@unit), notice: 'Estudande foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to unit_students_url(@unit), notice: 'Estudante removido com sucesso.'
  end

  private
    def set_unit
      @unit = school.units.find(params[:unit_id])
    end

    def set_student
      @student = @unit.students.find(params[:id])
    end

    def student_params
      params.require(:student).permit(
        :name, 
        :registration, 
        :birthday, 
        course_ids: [], 
        legal_guardians_attributes: [:id, :name, :phone, :email, :_destroy]
      )
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.slim
.row
  .col-xs-12.col-xs-offset-0.col-md-8.col-md-offset-2
    = form_for [@unit, @student] do |f|
      - if @student.errors.any?
        #error_explanation
          h2 = "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
          ul
            - @student.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .row
        .col-xs-12.col-md-6
          .form-group
            = f.label :registration
            = f.text_field :registration, class: "form-control"
        .col-xs-12.col-md-6
          .form-group
            = f.label :birthday
            = f.text_field :birthday, class: "form-control"
      .form-group
        = f.label :courses
        br
        = f.collection_check_boxes(:course_ids, @unit.courses, :id, :name) do |b|
          = b.check_box
          = b.label
      = f.fields_for :legal_guardians do |lg|
        = render 'legal_guardian_fields', f: lg
      .links
        = link_to_add_association 'Add', f, :legal_guardians

      .actions = f.submit nil, class: "btn flat-btn"

app/views/students/_legal_guardian_fields.html.slim
.nested-fields
  .row
    .col-xs-5.col-md-4
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
    .col-xs-5.col-md-4
      .form-group
        = f.label :email
        = f.text_field :email, class: "form-control"
    .col-xs-12.col-md-3.hidden-xs
      .form-group
        = f.label :phone
        = f.text_field :phone, class: "form-control"
    .col-xs-1.col-md-1
      .padding-right[style="padding-top: 28px"]
        = link_to_remove_association f, class: "btn btn-danger" do
          i.glyphicon.glyphicon-remove

app/views/students/edit.html.slim
- content_for :title do
  = "Edição estudante"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Voltar', unit_students_path(@unit)
== render 'form'

app/views/students/index.html.slim
- content_for :title do
  = "Estudantes"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Novo estudante', new_unit_student_path(@unit)
      '   |
      = link_to 'Voltar', units_path

.row
  - @students.each do |student|
    .col-sm-6
      .panel
        .panel-body.p-t-10
          .media-main
            a.pull-left[href="#"]
              img.thumb-lg.img-circle.bx-s[src="http://bootdey.com/img/Content/user_1.jpg" alt=""]
            .pull-right.btn-group-sm
              = link_to(edit_unit_student_path(student.unit, student), class: "btn btn-success") do 
                i.glyphicon.glyphicon-pencil
              = link_to(unit_student_path(student.unit, student), class: "btn btn-danger", data: { confirm: 'Are you sure?' }, method: :delete) do
                i.glyphicon.glyphicon-remove
            .info
              h4 = student.name
              p.text-muted = student.birthday
.row
  = paginate @students

app/views/students/new.html.slim
- content_for :title do
  = "Novo estudante"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Voltar', unit_students_path(@unit)
== render 'form'

app/views/students/show.html.slim
p#notice = notice

p
  strong Name:
  = @student.name
p
  strong Registration:
  = @student.registration
p
  strong Birthday:
  = @student.birthday

= link_to 'Edit', edit_unit_student_path(@unit, @student)
'|
= link_to 'Back', unit_students_path(@unit)