config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :school, only: [:new, :create, :update], path_names: {new: ''}
  root to: 'home#index'

  resources :units, except: [:show] do
    resources :teachers
    resources :students
    resources :courses
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :unit, counter_cache: true

  validates :unit, presence: true
  validates :name, presence: true
  validates :email, presence: true, format: { with: Devise::email_regexp }
  validates :phone, presence: true
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  include SetSchool
  before_action :set_unit
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = @unit.teachers.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @teacher = @unit.teachers.build
  end

  def edit
  end

  def create
    @teacher = @unit.teachers.build(teacher_params)

    if @teacher.save
      redirect_to unit_teachers_path(@unit), notice: "Professor foi criado com sucesso."
    else
      render :new
    end
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to unit_teachers_path(@unit), notice: "Professor foi atualizado com sucesso."
    else
      render :edit
    end
  end

  def destroy
    begin
      @teacher.destroy
      redirect_to unit_teachers_url(@unit), notice: "O Professor foi removido com sucesso"
    rescue ActiveRecord::InvalidForeignKey
      redirect_to unit_teachers_url(@unit), notice: "Não foi possível remover o professor, o mesmo se encontra vinculado com um curso."
    end
    
  end

  private
    def set_unit
      @unit = school.units.find(params[:unit_id])
    end

    def set_teacher
      @teacher = @unit.teachers.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:name, :email, :phone)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.slim
.row
  .col-xs-12.col-xs-offset-0.col-md-6.col-md-offset-3
    = form_for [@unit, @teacher] do |f|
      - if @teacher.errors.any?
        #error_explanation
          h2 = "#{pluralize(@teacher.errors.count, "error")} prohibited this teacher from being saved:"
          ul
            - @teacher.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .row
        .col-xs-12.col-md-6
          .form-group
            = f.label :email
            = f.text_field :email, class: "form-control"
        .col-xs-12.col-md-6
          .form-group
            = f.label :phone
            = f.text_field :phone, class: "form-control"
      .actions = f.submit nil, class: "btn flat-btn"

app/views/teachers/edit.html.slim
.row
  .col-sm-12.col-md-12
    h4.text-center.title-page New Teacher
    .text-center.btn-group-sm
      = link_to 'Back', unit_teachers_path(@unit)
== render 'form'

app/views/teachers/index.html.slim
- content_for :title do
  = "Professores"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Novo professor', new_unit_teacher_path(@unit)
      '   |
      = link_to 'Voltar', units_path

.row
  - @teachers.each do |teacher|
    .col-sm-6
      .panel.hvr-grow
        .panel-body.p-t-10
          .media-main
            a.pull-left[href="#"]
              img.thumb-lg.img-circle.bx-s[src="#{teacher.avatar}" alt=""]
            .pull-right.btn-group-sm
              = link_to(edit_unit_teacher_path(teacher.unit, teacher), class: "btn btn-success") do 
                i.glyphicon.glyphicon-pencil
              = link_to(unit_teacher_path(teacher.unit, teacher), class: "btn btn-danger", data: { confirm: 'Are you sure?' }, method: :delete) do
                i.glyphicon.glyphicon-remove
            .info
              h4 = teacher.name
              p.text-muted = teacher.phone
              p.text-muted = teacher.email
= paginate @teachers

app/views/teachers/new.html.slim
- content_for :title do
  = "Novo professor"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Voltar', unit_teachers_path(@unit)
== render 'form'

app/views/teachers/show.html.slim
p
  strong Name:
  = @teacher.name
p
  strong Email:
  = @teacher.email
p
  strong Phone:
  = @teacher.phone
p
  strong Unit:
  = @teacher.unit.name

= link_to 'Edit', edit_unit_teacher_path(@unit, @teacher)
'|
= link_to 'Back', teachers_path