config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :school, only: [:new, :create, :update], path_names: {new: ''}
  root to: 'home#index'

  resources :units, except: [:show] do
    resources :teachers
    resources :students
    resources :courses
  end
end

app/models/school.rb
class School < ApplicationRecord
  has_many :units

  validates :name, presence: true
  validates :email, presence: true, format: {with: Devise::email_regexp}
  validates :phone, presence: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  skip_before_action :verify_complete_sign_up
  def new
    @school = current_user.school || current_user.build_school
  end

  def update
    @school = current_user.school
    if @school.update(school_params)
      redirect_to root_path, notice: 'Escola foi criada com sucesso.'
    else
      render :new
    end
  end

  def create 
    @school = current_user.build_school(school_params)
    if @school.save
      current_user.completed!
      redirect_to root_path, notice: 'Escola foi atualizada com sucesso.'
    else
      render :new
    end
  end

  private 
    def school_params
      params.require(:school).permit(:name, :phone, :email)
    end
end

app/views/schools/new.html.slim
- content_for :title do
  = "Escola"
.row
  .col-xs-12.col-xs-offset-0.col-md-8.col-md-offset-2
    = form_for(@school, url: school_path) do |f|
      - if @school.errors.any?
        #error_explanation
          h2
            = pluralize(@school.errors.count, "error")
            |  prohibited this @school from being saved:
          ul
            - @school.errors.full_messages.each do |message|
              li
                = message
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .row
        .col-xs-12.col-md-7
          .form-group
            = f.label :email
            = f.text_field :email, class: "form-control"
        .col-xs-12.col-md-5
          .form-group
            = f.label :phone
            = f.text_field :phone, class: "form-control"
      .actions
        = f.submit nil, class: "btn flat-btn"