config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :school, only: [:new, :create, :update], path_names: {new: ''}
  root to: 'home#index'

  resources :units, except: [:show] do
    resources :teachers
    resources :students
    resources :courses
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
  has_many :teachers
  has_many :students
  has_many :courses

  validates :school, presence: true
  validates :name, presence: true
  validates :email, presence: true, format: {with: Devise::email_regexp}
  validates :phone, presence: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  include SetSchool
  before_action :set_unit, only: [:edit, :update, :destroy]

  def index
    @units = school.units
  end

  def new
    @unit = school.units.build
  end

  def edit
  end

  def create
    @unit = school.units.build(unit_params)

    if @unit.save
      redirect_to units_path, notice: "Unidade foi criada com sucesso."
    else
      render :new
    end
  end

  def update
    if @unit.update(unit_params)
      redirect_to units_path, notice: 'Unidade foi atualizada com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @unit.destroy
    redirect_to units_url, notice: 'Unidade foi removida com sucesso.'
  end

  private
    def set_unit
      @unit = school.units.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:name, :phone, :email, :address)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.slim
.row
  .col-xs-12.col-xs-offset-0.col-md-6.col-md-offset-3
    = form_for @unit do |f|
      - if @unit.errors.any?
        #error_explanation
          h2 = "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
          ul
            - @unit.errors.full_messages.each do |message|
              li = message
      
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .row
        .col-xs-12.col-md-4
          .form-group
            = f.label :phone
            = f.text_field :phone, class: "form-control"
        .col-xs-12.col-md-8
          .form-group
            = f.label :email
            = f.text_field :email, class: "form-control"
      .form-group
        = f.label :address
        = f.text_field :address, class: "form-control"
      .actions = f.submit nil, class: "btn flat-btn"

app/views/units/edit.html.slim
- content_for :title do
  = "Edição unidade"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Back', units_path
== render 'form'

app/views/units/index.html.slim
- content_for :title do
  = "Unidades"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Nova unidade', new_unit_path, id: "new_unit_link"

.row
  - @units.each do |unit|
    .col-sm-6
      .panel
        .panel-body.p-t-10
          .media-main
            .pull-right.btn-group-sm
              = link_to(edit_unit_path(unit), class: "btn btn-success") do 
                i.glyphicon.glyphicon-pencil
              = link_to(unit, class: "btn btn-danger", data: { confirm: 'Are you sure?' }, method: :delete) do
                i.glyphicon.glyphicon-remove
            .info
              h4.upcase = unit.name
              p.text-muted = unit.phone
              p.text-muted = unit.email
              p.text-muted = unit.address
          .clearfix
          hr
          .contact-footer.bottom-action.text-center
            .row
              .col-md-4.border
                = link_to 'Estudantes', unit_students_path(unit)
              .col-md-4.border
                = link_to 'Professores', unit_teachers_path(unit)
              .col-md-4.border
                = link_to 'Cursos', unit_courses_path(unit)

app/views/units/new.html.slim
- content_for :title do
  = "Nova unidade"
.row
  .col-sm-12.col-md-12
    .text-center.btn-group-sm
      = link_to 'Voltar', units_path
== render 'form'